### ISSUE TITLE
Can't compile in Geany

### ISSUE THREAD

**Issue by mcferrall** [eml2828/Lee_CSCI2270_FinalProject#1]
I prefer to use Geany and never really figured out CodeBlocks, so I am running your code in Geany. However, the code does not compile and I receive the error "In function 'int main()': 41:36: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings] readFileIntoTree(mt, "Test.txt");"

**Comment by eml2828** [comment]
What flags are you using to compile? Try 
g++ -Wall -fexceptions -std=c++11 -g  -c 
That is what I am using on codeblocks.
@mcferrall
