### ISSUE TITLE
PG-13 rating as invalid input

### ISSUE THREAD

**Issue by mcferrall** [eml2828/Lee_CSCI2270_FinalProject#2]
If a user inputs "PG-13" when trying to print by rating, the program says it is "Invalid Input" (even though there are PG-13 movies in the file).

**Comment by mcferrall** [comment]
The program also does not quit is the user inputs "10" after seeing "Invalid Input".

**Comment by eml2828** [comment]
@mcferrall 
For the "PG-13" error, did you just enter 7 and then enter PG-13 when prompted? I tried to recreate the error and could not. For the second issue, you need to hit enter after seeing invalid input, so that the menu will show up again before you can quit.
